-- GainStageJsfx.lua
-- Produces the text of Effects/GainStageEQ/GainStageEQTrim.jsfx (the OPTIONAL trim used when
-- "Apply gain via" is set to "JSFX trim"). Pure Lua: used by the build script and by the app
-- itself, which installs the file the first time it is needed.

local Core = require("GainStageCore")
local J = {}

J.FILE = "GainStageEQTrim.jsfx"
J.DIR = "GainStageEQ"
J.FX_NAME = "JS:GainStageEQ/GainStageEQTrim"   -- what TrackFX_AddByName is given
J.DESC = "GainStageEQ Trim"                     -- the desc: line; used to find the FX in a chain again

function J.text()
  local v = Core.VERSION
  return string.format([[
desc:%s
tags:utility gain
// Gain Stage EQ v%s - GENERATED by GainStageEQ.lua / tools/build.lua. Do not edit by hand.
// A plain gain in dB with a short glide (no zipper noise). The Gain Stage EQ action sets it
// when "Apply gain via" is "JSFX trim"; you can also use it on its own.

slider1:0<-60,24,0.01>Trim (dB)

@init
jsfx_version = %d;
g = 1;
tgt = 1;

@slider
tgt = 10^(slider1/20);
coef = 1 - exp(-1/(0.010*srate));

@sample
g += (tgt - g) * coef;
spl0 *= g;
spl1 *= g;

@gfx 260 26
gfx_set(0.85, 0.85, 0.85, 1);
gfx_x = 8; gfx_y = 6;
gfx_drawstr(sprintf(#, "Gain Stage EQ trim v%s: %%+.2f dB", slider1));
]], J.DESC, v, Core.version_code(v), v)
end

return J
